//! One-Time Pad (OTP) Cryptographic Engine
//! Information-theoretically secure encryption executing in x86_64 assembly.

use crate::ffi::{fill_secure_random, otp_xor_asm, secure_zeroize};

/// Container holding One-Time Pad encrypted data and the associated ephemeral pad.
#[derive(Debug, Clone)]
pub struct OtpEncryptedBlob {
    /// Ciphertext generated by XORing plaintext with pad
    pub ciphertext: Vec<u8>,
    /// Ephemeral One-Time Pad (true random entropy)
    pub pad: Vec<u8>,
}

impl Drop for OtpEncryptedBlob {
    fn drop(&mut self) {
        // Zeroize the pad and ciphertext memory upon drop
        secure_zeroize(&mut self.pad);
        secure_zeroize(&mut self.ciphertext);
    }
}

/// Encrypts plaintext bytes using a freshly generated One-Time Pad via assembly XOR.
pub fn otp_encrypt(plaintext: &[u8]) -> Result<OtpEncryptedBlob, String> {
    if plaintext.is_empty() {
        return Ok(OtpEncryptedBlob {
            ciphertext: Vec::new(),
            pad: Vec::new(),
        });
    }

    let len = plaintext.len();
    let mut pad = vec![0u8; len];
    fill_secure_random(&mut pad)?;

    let mut ciphertext = vec![0u8; len];
    otp_xor_asm(plaintext, &pad, &mut ciphertext);

    Ok(OtpEncryptedBlob { ciphertext, pad })
}

/// Decrypts ciphertext bytes using the provided One-Time Pad via assembly XOR.
pub fn otp_decrypt(ciphertext: &[u8], pad: &[u8]) -> Result<Vec<u8>, String> {
    if ciphertext.len() != pad.len() {
        return Err(format!(
            "OTP Error: Ciphertext length ({}) does not match Pad length ({})",
            ciphertext.len(),
            pad.len()
        ));
    }

    if ciphertext.is_empty() {
        return Ok(Vec::new());
    }

    let mut plaintext = vec![0u8; ciphertext.len()];
    otp_xor_asm(ciphertext, pad, &mut plaintext);

    Ok(plaintext)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_otp_roundtrip() {
        let message = b"OUIJA TOP SECRET TRANSMISSION 2026";
        let blob = otp_encrypt(message).expect("OTP encrypt failed");
        assert_ne!(&blob.ciphertext[..], message);

        let decrypted = otp_decrypt(&blob.ciphertext, &blob.pad).expect("OTP decrypt failed");
        assert_eq!(&decrypted[..], message);
    }
}
